[connections.default]
warehouse = "DEVOPS_WH"
role = "SYSADMIN"
database = "GITHUB"
schema = "SNOWFLAKE_GIT"
account = "<INSERT YOUR ACCOUNT IDENTIFIER>"
user = "<INSERT YOUR USERNAME>"
password = "<INSERT YOUR PASSWORD>"