name: Deploy data pipeline

on:
  push:
    branches:
      - main
      - DST-*  # Trigger on pushes to branches starting with "DST-"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      REPO_NAME: "SOORYA_TEST.GITHUB.GITHUB_REPO"
      # Read connection secrets
      SNOWFLAKE_CONNECTIONS_DEFAULT_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_CONNECTIONS_DEFAULT_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_CONNECTIONS_DEFAULT_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}

    steps:
      # Checkout step is necessary if you want to use a config file from your repo
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get list of changed files
        id: changed_files
        run: |
          # Fetch the main branch for comparison
          git fetch origin main
          
          # Get the list of changed files
          git diff --name-only origin/main...HEAD > changed_files.txt
          
          # Output the file list
          echo "Changed files:"
          cat changed_files.txt
          
          # Set the list as an output variable
          changed_files=$(cat changed_files.txt | tr '\n' ' ')
          echo "changed_files=$changed_files" >> $GITHUB_ENV

      - name: Use the changed files
        run: |
          echo "The changed files are: ${{ env.changed_files }}"

      # Install Snowflake CLI GitHub Action and point to config file
      - name: Install snowflake-cli
        uses: Snowflake-Labs/snowflake-cli-action@v1.5
        with:
          cli-version: "latest"
          default-config-file-path: ".snowflake/config.toml"

      # Update Snowflake's copy of the repository
      - name: Fetch repository changes
        run: snow git fetch "${REPO_NAME}"
