name: Deploy data pipeline

on:
  push:
    branches:
      - main
      - DST-*  # Trigger on pushes to branches starting with "DST-"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      REPO_NAME: "SOORYA_TEST.GITHUB.GITHUB_REPO"
      # Read connection secrets
      SNOWFLAKE_CONNECTIONS_DEFAULT_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_CONNECTIONS_DEFAULT_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_CONNECTIONS_DEFAULT_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}

    steps:
      # Checkout step is necessary if you want to use a config file from your repo
      - name: Github Actions - Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Github Actions - Get branch name
        id: branch_name
        run: |
          # Extract the branch name from GITHUB_REF
          branch_name=${GITHUB_REF#refs/heads/}
          echo "Branch name is: $branch_name"
          echo "branch_name=$branch_name" >> $GITHUB_ENV

      - name: Github Actions - Get list of changed files
        id: changed_files
        run: |
          # Fetch the main branch for comparison
          git fetch origin master
          
          # Get the list of changed files
          git diff --name-only origin/master...HEAD > changed_files.txt
          
          # Output the file list
          echo "Changed files:"
          cat changed_files.txt
          
          # Set the list as an output variable
          changed_files=$(cat changed_files.txt | tr '\n' ' ')
          echo "changed_files=$changed_files" >> $GITHUB_ENV

      - name: Github Actions - Use the changed files
        run: |
          echo "The changed files are: ${{ env.changed_files }}"

      # Install Snowflake CLI GitHub Action and point to config file
      - name: Github Actions - Install snowflake-cli
        uses: Snowflake-Labs/snowflake-cli-action@v1.5
        with:
          cli-version: "latest"
          default-config-file-path: ".snowflake/config.toml"

      # Update Snowflake's copy of the repository
      - name: Snowflake Step - Fetch repository changes
        run: snow git fetch "${REPO_NAME}"

      # Deploy SQLs in Snowflake
      - name: Snowflake Step - Execute Snowflake SQL scripts in order
        if: env.changed_files != ''
        run: |
          echo "Processing changed files: ${{ env.changed_files }}"
      
          # Define the execution order for database change management
          declare -a execution_order=("snowflake/database" "snowflake/schema" "snowflake/table")
      
          # Iterate over each execution level
          for level in "${execution_order[@]}"; do
            echo "Processing changes in $level"
            
            # Filter changed files for the current level (exclude .txt files)
            for file in ${{ env.changed_files }}; do
              # Check if the file belongs to the current level and is a SQL file
              if [[ $file == $level* && $file == *.sql ]]; then
                echo "Executing SQL script: $file"
                
                # Construct the Snowflake repository path for the file
                full_repo_path="@SOORYA_TEST.GITHUB.GITHUB_REPO/branches/${{ env.branch_name }}/$file"
                echo "Executing on repo path: $full_repo_path"
                
                # Execute the SQL script
                snow git execute "$full_repo_path"
              else
                echo "Skipping non-SQL file or file not in $level: $file"
              fi
            done
          done